name: My First Workflow
on: workflow_dispatch
jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - name: Print Greeting
          run: echo "Hello World"
        - name: Say Bye!
          run: |
              echo "Congrats Ace on completing the first github action workflow"
              echo "Good Bye!"
